services:
  database:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auto-prime
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5431:5432

volumes:
  postgres_data:
